"""
train.py — train, evaluate, quantize to int8, and export a C header.

Inputs:  data/windows.npz   (built by prepare_data.py)
Outputs: artifacts/model.keras
         artifacts/model.tflite
         artifacts/model_data.h   <- the file the firmware will include
"""

import os

import numpy as np
import tensorflow as tf
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

DATA_PATH = "data/windows.npz"
ARTIFACTS = "artifacts"
EPOCHS    = 50
BATCH     = 64
SEED      = 42


# ── Model ─────────────────────────────────────────────────────────────
def build_model(input_shape, num_classes):
    """Small 1-D CNN. ~10k params, designed to quantize cleanly to int8."""
    inputs = tf.keras.Input(shape=input_shape)
    x = tf.keras.layers.Conv1D(16, 5, padding="same", activation="relu")(inputs)
    x = tf.keras.layers.MaxPool1D(2)(x)
    x = tf.keras.layers.Conv1D(32, 5, padding="same", activation="relu")(x)
    x = tf.keras.layers.MaxPool1D(2)(x)
    x = tf.keras.layers.Conv1D(64, 3, padding="same", activation="relu")(x)
    x = tf.keras.layers.GlobalAveragePooling1D()(x)
    outputs = tf.keras.layers.Dense(num_classes, activation="softmax")(x)
    return tf.keras.Model(inputs, outputs)


# ── Export ────────────────────────────────────────────────────────────
def write_c_header(path, model_bytes, classes, mean, std):
    with open(path, "w") as f:
        w = f.write
        w("// AUTO-GENERATED by tools/ml/train.py — do not edit by hand.\n")
        w("#pragma once\n#include <cstdint>\n\n")
        w(f"constexpr int kNumClasses = {len(classes)};\n")
        w("constexpr const char* kClassLabels[] = {\n")
        for c in classes:
            w(f'  "{c}",\n')
        w("};\n\n")
        w("constexpr float kInputMean[6] = {"
          + ", ".join(f"{v:.6f}f" for v in mean) + "};\n")
        w("constexpr float kInputStd[6]  = {"
          + ", ".join(f"{v:.6f}f" for v in std) + "};\n\n")
        w(f"constexpr unsigned int kModelLen = {len(model_bytes)};\n")
        w("alignas(8) const unsigned char kModelData[] = {\n")
        hex_bytes = [f"0x{b:02x}" for b in model_bytes]
        for i in range(0, len(hex_bytes), 16):
            w("  " + ", ".join(hex_bytes[i:i + 16]) + ",\n")
        w("};\n")


# ── Main ──────────────────────────────────────────────────────────────
def main():
    os.makedirs(ARTIFACTS, exist_ok=True)
    tf.keras.utils.set_random_seed(SEED)

    print(f"[train] loading {DATA_PATH}")
    data    = np.load(DATA_PATH, allow_pickle=True)
    X, y    = data["X"], data["y"]
    classes = list(data["classes"])
    mean    = data["mean"]
    std     = data["std"]
    y_idx   = np.array([classes.index(label) for label in y])

    X_tr, X_tmp, y_tr, y_tmp = train_test_split(
        X, y_idx, test_size=0.30, stratify=y_idx, random_state=SEED)
    X_va, X_te, y_va, y_te = train_test_split(
        X_tmp, y_tmp, test_size=0.50, stratify=y_tmp, random_state=SEED)
    print(f"[train] splits: train={len(X_tr)}  val={len(X_va)}  test={len(X_te)}")

    model = build_model(X.shape[1:], len(classes))
    model.summary()
    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )

    model.fit(
        X_tr, y_tr,
        validation_data=(X_va, y_va),
        epochs=EPOCHS, batch_size=BATCH,
        callbacks=[
            tf.keras.callbacks.EarlyStopping(patience=8, restore_best_weights=True),
            tf.keras.callbacks.ReduceLROnPlateau(patience=3, factor=0.5),
        ],
        verbose=2,
    )

    _, test_acc = model.evaluate(X_te, y_te, verbose=0)
    print(f"\n[train] test accuracy: {test_acc:.4f}")
    y_pred = model.predict(X_te, verbose=0).argmax(axis=1)
    print(classification_report(y_te, y_pred, target_names=classes))

    keras_path = os.path.join(ARTIFACTS, "model.keras")
    model.save(keras_path)
    print(f"[train] saved {keras_path}")

    # ── Quantize ──
    def representative_data():
        idx = np.random.default_rng(SEED).choice(
            len(X_tr), size=min(500, len(X_tr)), replace=False)
        for i in idx:
            yield [X_tr[i:i + 1].astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations            = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset   = representative_data
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type     = tf.int8
    converter.inference_output_type    = tf.int8
    tflite_bytes = converter.convert()

    tflite_path = os.path.join(ARTIFACTS, "model.tflite")
    with open(tflite_path, "wb") as f:
        f.write(tflite_bytes)
    print(f"[train] saved {tflite_path} ({len(tflite_bytes)} bytes)")

    header_path = os.path.join(ARTIFACTS, "model_data.h")
    write_c_header(header_path, tflite_bytes, classes, mean, std)
    print(f"[train] saved {header_path}")


if __name__ == "__main__":
    main()
